export const MOCK_NEWS_DETAIL = {
  id: 12,
  public_id: 'a2c9e3b1-7d42-4a7f-b7e1-8b6e5bcd9123',
  title: 'Trí tuệ nhân tạo đang thay đổi ngành thương mại điện tử như thế nào?',
  slug: 'tri-tue-nhan-tao-thay-doi-thuong-mai-dien-tu',
  excerpt:
    'AI không chỉ giúp cá nhân hóa trải nghiệm mua sắm mà còn tối ưu vận hành, logistics và marketing trong thương mại điện tử. AI không chỉ giúp cá nhân hóa trải nghiệm mua sắm mà còn tối ưu vận hành, logistics và marketing trong thương mại điện tử. AI không chỉ giúp cá nhân hóa trải nghiệm mua sắm mà còn tối ưu vận hành, logistics và marketing trong thương mại điện tử. AI không chỉ giúp cá nhân hóa trải nghiệm mua sắm mà còn tối ưu vận hành, logistics và marketing trong thương mại điện tử.',
  content_html:
    '<p>Trí tuệ nhân tạo (AI) đang trở thành yếu tố then chốt trong sự phát triển của thương mại điện tử hiện đại.</p><p>Các doanh nghiệp ngày nay sử dụng AI để phân tích hành vi người dùng, đề xuất sản phẩm, tối ưu giá bán và dự đoán nhu cầu.</p><p>Ngoài ra, AI còn được ứng dụng trong chatbot chăm sóc khách hàng, quản lý kho thông minh và tự động hóa marketing.</p><p>Trong tương lai, AI hứa hẹn sẽ tiếp tục tạo ra những đột phá lớn, giúp doanh nghiệp thương mại điện tử cạnh tranh hiệu quả hơn.</p>',
  status: 'published',
  meta_title: 'AI và tương lai của thương mại điện tử',
  meta_description:
    'Khám phá cách trí tuệ nhân tạo đang làm thay đổi thương mại điện tử từ cá nhân hóa đến tối ưu vận hành.',
  content_assets: [
    {
      position: 1,
      caption: 'AI cá nhân hóa trải nghiệm mua sắm trực tuyến',
      asset: {
        id: 101,
        public_id: 'img-ai-ecommerce-01',
        url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71',
        mime_type: 'image/jpeg',
        byte_size: 245678,
        width: 1920,
        height: 1080,
      },
    },
    {
      position: 2,
      caption: 'Hệ thống phân tích dữ liệu lớn trong thương mại điện tử',
      asset: {
        id: 102,
        public_id: 'img-ai-ecommerce-02',
        url: 'https://images.unsplash.com/photo-1556155092-8707de31f9c4',
        mime_type: 'image/jpeg',
        byte_size: 312450,
        width: 1920,
        height: 1280,
      },
    },
    {
      position: 3,
      caption: 'Chatbot AI hỗ trợ khách hàng 24/7',
      asset: {
        id: 103,
        public_id: 'img-ai-ecommerce-03',
        url: 'https://images.unsplash.com/photo-1581090700227-1e37b190418e',
        mime_type: 'image/jpeg',
        byte_size: 198340,
        width: 1600,
        height: 1067,
      },
    },
    {
      position: 4,
      caption: 'Quản lý kho thông minh với AI',
      asset: {
        id: 104,
        public_id: 'img-ai-ecommerce-04',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d',
        mime_type: 'image/jpeg',
        byte_size: 287901,
        width: 1920,
        height: 1280,
      },
    },
    {
      position: 5,
      caption: 'Quản lý kho thông minh với AI1',
      asset: {
        id: 105,
        public_id: 'img-ai-ecommerce-04',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d',
        mime_type: 'image/jpeg',
        byte_size: 287901,
        width: 1920,
        height: 1280,
      },
    },
    {
      position: 6,
      caption: 'Quản lý kho thông minh với AI1',
      asset: {
        id: 106,
        public_id: 'img-ai-ecommerce-04',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d',
        mime_type: 'image/jpeg',
        byte_size: 287901,
        width: 1920,
        height: 1280,
      },
    },
    {
      position: 7,
      caption: 'Quản lý kho thông minh với AI1',
      asset: {
        id: 107,
        public_id: 'img-ai-ecommerce-04',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d',
        mime_type: 'image/jpeg',
        byte_size: 287901,
        width: 1920,
        height: 1280,
      },
    },
  ],
  published_at: '2026-01-05T09:30:00.000Z',
  created_at: '2026-01-01T08:15:00.000Z',
  updated_at: '2026-01-08T14:45:12.000Z',
} as const
